import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)


#Data profiling
#1.  Identify the dataset’s number of records (i.e., rows) and number of variables (i.e., columns).
df= pd.read_csv('mental_health.csv')


#2.  List each variable and indicate the variable’s data type (quantitative/numerical or qualitative/categorical) and data subtype (i.e., continuous/discrete or nominal/ordinal).
print("Variables are: ", df.columns.tolist())
print("_" * 100)
print(" ")
print("Variables data type and data subtype are: \n ")
print("Person_ID: Qualitative/Categorical, Nominal")
print("Age: Quantitative/Numerical, Discrete")
print("Gender: Qualitative/Categorical, Nominal")
print("Occupation: Qualitative/Categorical, Nominal")
print("Daily_Screen_Time: Quantitative/Numerical, Continuous")
print("Social_Media_Usage: Qualitative/Categorical, Ordinal")
print("Night_Usage: Qualitative/Categorical, Nominal")
print("Sleep_Hours: Quantitative/Numerical, Continuous")
print("Stress_Level: Qualitative/Categorical, Ordinal")
print("Work_Study_Hours: Quantitative/Numerical, Continuous")
print("Physical_Activity: Quantitative/Numerical, Continuous")
print("Social_Interaction_Score: Quantitative/Numerical, Discrete")
print("Caffeine_Intake: Quantitative/Numerical, Continuous")
print("Smoking: Qualitative/Categorical, Nominal")
print("Alcohol: Qualitative/Categorical, Nominal")
print("Depression: Qualitative/Categorical, Nominal")
print("Anxiety: Qualitative/Categorical, Nominal")
print("Burnout: Qualitative/Categorical, Nominal")
print("_" * 100)
print(" ")
#duplicates:
print("\nDuplicate check for all individual columns: ")
print(" ")
#Storing duplicates for each column on a new variable
Person_ID_duplicates = df[df.duplicated(subset=['Person_ID'])]['Person_ID'].count()
Age_duplicates = df[df.duplicated(subset=['Age'])]['Age'].count()
Gender_duplicates = df[df.duplicated(subset=['Gender'])]['Gender'].count()
Occupation_duplicates = df[df.duplicated(subset=['Occupation'])]['Occupation'].count()
Daily_Screen_Time_duplicates = df[df.duplicated(subset=['Daily_Screen_Time'])]['Daily_Screen_Time'].count()
Social_Media_Usage_duplicates = df[df.duplicated(subset=['Social_Media_Usage'])]['Social_Media_Usage'].count()
Night_Usage_duplicates = df[df.duplicated(subset=['Night_Usage'])]['Night_Usage'].count()
Sleep_Hours_duplicates = df[df.duplicated(subset=['Sleep_Hours'])]['Sleep_Hours'].count()
Stress_Level_duplicates = df[df.duplicated(subset=['Stress_Level'])]['Stress_Level'].count()
Work_Study_Hours_duplicates = df[df.duplicated(subset=['Work_Study_Hours'])]['Work_Study_Hours'].count()
Physical_Activity_duplicates = df[df.duplicated(subset=['Physical_Activity'])]['Physical_Activity'].count()
Social_Interaction_Score_duplicates = df[df.duplicated(subset=['Social_Interaction_Score'])]['Social_Interaction_Score'].count()
Caffeine_Intake_duplicates = df[df.duplicated(subset=['Caffeine_Intake'])]['Caffeine_Intake'].count()
Smoking_duplicates = df[df.duplicated(subset=['Smoking'])]['Smoking'].count()
Alcohol_duplicates = df[df.duplicated(subset=['Alcohol'])]['Alcohol'].count()
Depression_duplicates = df[df.duplicated(subset=['Depression'])]['Depression'].count()
Anxiety_duplicates = df[df.duplicated(subset=['Anxiety'])]['Anxiety'].count()
Burnout_duplicates = df[df.duplicated(subset=['Burnout'])]['Burnout'].count()

df = df.drop_duplicates(subset=['Person_ID'], keep='first')

print("Person_ID duplicates: ", Person_ID_duplicates)
print("Age duplicates: ", Age_duplicates)
print("Gender duplicates: ", Gender_duplicates)
print("Occupation duplicates: ", Occupation_duplicates)
print("Daily_Screen_Time duplicates: ", Daily_Screen_Time_duplicates)
print("Social_Media_Usage duplicates: ", Social_Media_Usage_duplicates)
print("Night_Usage duplicates: ", Night_Usage_duplicates)
print("Sleep_Hours duplicates: ", Sleep_Hours_duplicates)
print("Stress_Level duplicates: ", Stress_Level_duplicates)
print("Work_Study_Hours duplicates: ", Work_Study_Hours_duplicates)
print("Physical_Activity duplicates: ", Physical_Activity_duplicates)
print("Social_Interaction_Score duplicates: ", Social_Interaction_Score_duplicates)
print("Caffeine_Intake duplicates: ", Caffeine_Intake_duplicates)
print("Smoking duplicates: ", Smoking_duplicates)
print("Alcohol duplicates: ", Alcohol_duplicates)
print("Depression duplicates: ", Depression_duplicates)
print("Anxiety duplicates: ", Anxiety_duplicates)
print("Burnout duplicates: ", Burnout_duplicates)

#Checking for missing values:

Person_ID_Missing_values = df['Person_ID'].isnull().sum()
Age_Missing_values = df['Age'].isnull().sum()
Gender_Missing_values = df['Gender'].isnull().sum()
Occupation_Missing_values = df['Occupation'].isnull().sum()
Daily_Screen_Time_Missing_values = df['Daily_Screen_Time'].isnull().sum()
Social_Media_Usage_Missing_values = df['Social_Media_Usage'].isnull().sum()
Night_Usage_Missing_values = df['Night_Usage'].isnull().sum()
Sleep_Hours_Missing_values = df['Sleep_Hours'].isnull().sum()
Stress_Level_Missing_values = df['Stress_Level'].isnull().sum()
Work_Study_Hours_Missing_values = df['Work_Study_Hours'].isnull().sum()
Physical_Activity_Missing_values = df['Physical_Activity'].isnull().sum()
Social_Interaction_Score_Missing_values = df['Social_Interaction_Score'].isnull().sum()
Caffeine_Intake_Missing_values = df['Caffeine_Intake'].isnull().sum()
Smoking_Missing_values = df['Smoking'].isnull().sum()
Alcohol_Missing_values = df['Alcohol'].isnull().sum()
Depression_Missing_values = df['Depression'].isnull().sum()
Anxiety_Missing_values = df['Anxiety'].isnull().sum()
Burnout_Missing_values = df['Burnout'].isnull().sum()
print("_" * 100)
print(" ")
print("Missing Value Check: ")
print(" ")
print("Person_ID Missing values: ", Person_ID_Missing_values)
print("Age Missing values: ", Age_Missing_values)
print("Gender Missing values: ", Gender_Missing_values)
print("Occupation Missing values: ", Occupation_Missing_values)
print("Daily_Screen_Time Missing values: ", Daily_Screen_Time_Missing_values)
print("Social_Media_Usage Missing values: ", Social_Media_Usage_Missing_values)
print("Night_Usage Missing values: ", Night_Usage_Missing_values)
print("Sleep_Hours Missing values: ", Sleep_Hours_Missing_values)
print("Stress_Level Missing values: ", Stress_Level_Missing_values)
print("Work_Study_Hours Missing values: ", Work_Study_Hours_Missing_values)
print("Physical_Activity Missing values: ", Physical_Activity_Missing_values)
print("Social_Interaction_Score Missing values: ", Social_Interaction_Score_Missing_values)
print("Caffeine_Intake Missing values: ", Caffeine_Intake_Missing_values)
print("Smoking Missing values: ", Smoking_Missing_values)
print("Alcohol Missing values: ", Alcohol_Missing_values)
print("Depression Missing values: ", Depression_Missing_values)
print("Anxiety Missing values: ", Anxiety_Missing_values)
print("Burnout Missing values: ", Burnout_Missing_values)
print("_" * 100)
print(" ")

Person_ID_Unique_values = df['Person_ID'].unique()
Age_Unique_values = df['Age'].unique()
Gender_Unique_values = df['Gender'].unique()
Occupation_Unique_values = df['Occupation'].unique()
Daily_Screen_Time_Unique_values = df['Daily_Screen_Time'].unique()
Social_Media_Usage_Unique_values = df['Social_Media_Usage'].unique()
Night_Usage_Unique_values = df['Night_Usage'].unique()
Sleep_Hours_Unique_values = df['Sleep_Hours'].unique()
Stress_Level_Unique_values = df['Stress_Level'].unique()
Work_Study_Hours_Unique_values = df['Work_Study_Hours'].unique()
Physical_Activity_Unique_values = df['Physical_Activity'].unique()
Social_Interaction_Score_Unique_values = df['Social_Interaction_Score'].unique()
Caffeine_Intake_Unique_values = df['Caffeine_Intake'].unique()
Smoking_Unique_values = df['Smoking'].unique()
Alcohol_Unique_values = df['Alcohol'].unique()
Depression_Unique_values = df['Depression'].unique()
Anxiety_Unique_values = df['Anxiety'].unique()
Burnout_Unique_values = df['Burnout'].unique()

print("Person_ID Unique values: ", Person_ID_Unique_values, "\n")
print("Age Unique values: ", Age_Unique_values, "\n")
print("Gender Unique values: ", Gender_Unique_values, "\n")
print("Occupation Unique values: ", Occupation_Unique_values, "\n")
print("Daily_Screen_Time Unique values: ", Daily_Screen_Time_Unique_values, "\n")
print("Social_Media_Usage Unique values: ", Social_Media_Usage_Unique_values, "\n")
print("Night_Usage Unique values: ", Night_Usage_Unique_values, "\n")
print("Sleep_Hours Unique values: ", Sleep_Hours_Unique_values, "\n")
print("Stress_Level Unique values: ", Stress_Level_Unique_values, "\n")
print("Work_Study_Hours Unique values: ", Work_Study_Hours_Unique_values, "\n")
print("Physical_Activity Unique values: ", Physical_Activity_Unique_values, "\n")
print("Social_Interaction_Score Unique values: ", Social_Interaction_Score_Unique_values, "\n")
print("Caffeine_Intake Unique values: ", Caffeine_Intake_Unique_values, "\n")
print("Smoking Unique values: ", Smoking_Unique_values, "\n")
print("Alcohol Unique values: ", Alcohol_Unique_values, "\n")
print("Depression Unique values: ", Depression_Unique_values, "\n")
print("Anxiety Unique values: ", Anxiety_Unique_values, "\n")
print("Burnout Unique values: ", Burnout_Unique_values, "\n")

df.info()
print(df.describe(include='all'))

print("_" * 100)
print(" ")
print("Outlier Check: \n")
num_cols = df.select_dtypes(include=['float64', 'int64']).columns

for col in num_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
    print(f"{col} Outliers: {len(outliers)}")
